### ISSUE TITLE
Every single feature idea I have

### ISSUE THREAD

**Issue by i-winxd** [Snazzah/catcut#1]
Mind-dump incoming! Only do the ones you think are feasible, though I believe *all* of them should be doable with FFMPEG according to my experience:

- Loudness normalization
   - You can currently set the volume between 0 and 200%, but in FFMPEG you can set the volume to target a particular loudness (such as -14LUFS). This feature exists in FFMPEG.
- Audio file support
   - Importing an audio file should be treated as a blank video

Okay that's everything so far.

**Comment by Snazzah** [comment]
I could add an option to set the decibel offset in the volume filter, if you could show what args you use to set LUFS that could also be done

As for audio editing, the plan was to have a new editor for that that would show the waveform and only have options normally for audio

**Comment by i-winxd** [comment]
Loudness: https://superuser.com/questions/1705712/is-ffmpeg-usable-with-audio-loudness-normalization

Applying normalization may increase or decrease the audio volume given the same loudness target, depending on how loud an input audio file is. There is an implicit "decibel" offset that is calculated based on that. I just used the stackoverflow command there

loudnesspenalty.com gives you that offset, but will only show you negative values

**Comment by Snazzah** [comment]
Added: https://github.com/Snazzah/catcut/commit/8661fa605fc6bde17744667c8be43c47747f3bdb https://github.com/Snazzah/catcut/commit/51df219f315e34b5e3b70f39062d7e097f0cc1ed
