### ISSUE TITLE
The video only appears after 4-5 seconds

### ISSUE THREAD

**Issue by KwiatekMiki** [Snazzah/catcut#4]
https://github.com/user-attachments/assets/4933b23b-4099-4a61-a9cc-05e9a2f4c720

Remuxing doesn't help and after uploading the video to YouTube, it shows this (that's the first frame of the video) until the time when the video shows up in VLC:

![image](https://github.com/user-attachments/assets/02719022-4dfd-4381-a4e5-cdfdcd9886db)

but it should show this:

![image](https://github.com/user-attachments/assets/70471e7a-0596-4f7b-87ad-59d0ee958998)

In the GitHub and Firefox video player it doesn't wait for the video.

https://github.com/user-attachments/assets/33ff3092-b73e-4470-aa42-9b8c0219197d

### Video links
Original: https://files.elonmusk.deals/u/mGrpLR.mp4
Trimmed: https://files.elonmusk.deals/u/q5Uneh.mp4
Trimmed after uploading to YouTube: https://youtu.be/H9P379Kb6_U 
Trimmed and remuxed: https://files.elonmusk.deals/u/OvigjU.mp4

**Comment by Snazzah** [comment]
Try re-encoding the video when trimming, trimming without re-encoding could have some errors sometimes.

**Comment by KwiatekMiki** [comment]
It worked, thanks! Sorry for the late reply, I only needed to trim a video now.
